<a href="https://colab.research.google.com/github/Chaki34/python-basics/blob/main/Student_Data_Analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np

In [94]:
marks = np.array([
    [85, 78, 92],
    [70, 65, 80],
    [90, 88, 91],
    [60, 30, 68],
    [75, 93, 37]
])

print(marks.shape)

print(marks)

(5, 3)
[[85 78 92]
 [70 65 80]
 [90 88 91]
 [60 30 68]
 [75 93 37]]


In [95]:
# Calculate average marks for each student (row-wise)
Student_avg = np.mean(marks, axis=1)
# np.mean() → finds average
# marks → your data (2D array: rows = students, columns = subjects)
# axis=1 → go across rows (-->), meaning each student separately

# Print the result
print("Avg Per Student", Student_avg)
# Displays the text + the calculated averages

Avg Per Student [85.         71.66666667 89.66666667 52.66666667 68.33333333]


In [96]:
# Calculate average marks for each subject (column-wise)
subject_avg = np.mean(marks, axis=0)
# np.mean() → finds average
# marks → 2D array (rows = students, columns = subjects)
# axis=0 → go down columns (⬇), meaning each subject separately

# Print the result
print("Subject Avg : ", subject_avg)
# Displays subject-wise averages

Subject Avg :  [76.  70.8 73.6]


In [97]:
# find highest and lowest value from the 2d array
print("higherst mark :",np.max(marks))
print("lowest mark : ",np.min(marks))

higherst mark : 93
lowest mark :  30


In [98]:
# Find highest mark for each student (row-wise)
best_per_student = np.max(marks, axis=1)
# np.max() → finds maximum value
# axis=1 → go across rows (each student)

# Print result
print("Best mark per student:", best_per_student)

Best mark per student: [92 80 91 68 93]


In [99]:
# Check pass/fail status for each student
pass_status = np.all(marks >= 40, axis=1)
# marks >= 40 → compares every mark with 40
#               returns True (pass) or False (fail) for each subject
# np.all(...) → checks if ALL values in a row are True
# axis=1 → go row-wise (each student)
# So → a student passes only if all their marks are ≥ 40

# Print the result
print("Pass status:", pass_status)
# Displays True (Pass) or False (Fail) for each student

Pass status: [ True  True  True False False]


In [100]:
#find topper
total_marks = np.sum(marks, axis=1)
topper_index = np.argmax(total_marks)
print("Topper is student index:", topper_index)

Topper is student index: 2


In [101]:
# Assign grades based on average
grades = np.where(Student_avg >= 85, "A",
         np.where(Student_avg >= 70, "B", "C"))
# If avg ≥ 85 → A
# Else if avg ≥ 70 → B
# Else → C

# Print results
print("Student Average:", Student_avg)
print("Grades:", grades)

Student Average: [85.         71.66666667 89.66666667 52.66666667 68.33333333]
Grades: ['A' 'B' 'A' 'C' 'C']


In [102]:
# how meny passed
num_passed = np.sum(pass_status)

print("Number of students passed:", num_passed)

Number of students passed: 3


In [103]:
# count  fail
num_failed = len(pass_status) - num_passed
print("Number of students failed:", num_failed)

Number of students failed: 2


In [104]:
pass_status = np.all(marks >= 40, axis=1)

num_passed = np.sum(pass_status)

print("Number of students passed:", num_passed)

Number of students passed: 3


In [105]:
subjects = ["Math", "Science", "English"]
# List of subject names (columns in marks array)

top_students = np.argmax(marks, axis=0)
# np.argmax() → returns index of maximum value
# axis=0 → column-wise (each subject)
# So → finds which student got highest mark in each subject

for i in range(len(subjects)):
    # Loop through each subject index

    print(subjects[i], "topper is Student", top_students[i])
    # Print subject name and student index (who scored highest)

Math topper is Student 2
Science topper is Student 4
English topper is Student 0
